2021-10-15 06:49:58.525 | INFO     |  5317 | __main__:main:46 | Starting Audio Service
2021-10-15 06:49:58.526 | INFO     |  5317 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-15 06:49:58.529 | INFO     |  5317 | mycroft_bus_client.client.client | Connected
2021-10-15 06:49:58.530 | INFO     |  5317 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-15 06:49:58.534 | WARNING  |  5317 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
2021-10-15 06:49:59.096 | ERROR    |  5317 | mycroft.tts.mimic_tts:validate_connection:226 | Mimic executable not found
2021-10-15 06:49:59.097 | ERROR    |  5317 | mycroft.tts.tts:create:625 | The TTS could not be loaded.
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 221, in validate_connection
    subprocess.call([mimic_bin, '--version'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 614, in create
    tts.validator.validate()
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 500, in validate
    self.validate_connection()
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 229, in validate_connection
    from err
Exception: Mimic was not found. Run install-mimic.sh to install it.
2021-10-15 06:49:59.138 | ERROR    |  5317 | __main__:on_error:37 | Audio service failed to launch (Exception('Mimic was not found. Run install-mimic.sh to install it.')).
2021-10-15 06:50:11.569 | ERROR    |  5317 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:50:42.452 | ERROR    |  5317 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:50:42.453 | ERROR    |  5317 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:50:58.547 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.548 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.548 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.548 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.548 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.548 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.549 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.549 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.549 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.549 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.549 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.549 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.550 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.550 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.550 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.550 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.550 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.550 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after interpreter shutdown
2021-10-15 06:50:58.551 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.551 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.551 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.551 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.551 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.552 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.552 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.552 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.552 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.552 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.553 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.553 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.553 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.553 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.553 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.553 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.553 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.554 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.554 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.554 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.554 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.554 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.571 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.571 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.571 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.571 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.571 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.572 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.572 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.572 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.572 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.575 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.575 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.575 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.575 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.575 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.576 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.576 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.576 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.576 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.576 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.576 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.576 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.577 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.577 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.577 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.577 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.577 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.577 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.578 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.578 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.578 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.578 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.578 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.604 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.604 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.604 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.604 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.604 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.605 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.605 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.605 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.605 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.605 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.605 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.606 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.606 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.606 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.606 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.606 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.627 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.627 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.627 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.627 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.627 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.628 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.628 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.628 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.628 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.628 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.628 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.629 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.629 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.629 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.629 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.629 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.630 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.630 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.630 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.650 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.651 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.655 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.655 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.655 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.655 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.655 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.656 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.656 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.656 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.656 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.656 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.656 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.657 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.657 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.657 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.657 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.657 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.657 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.658 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.658 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.658 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.658 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:50:58.658 | ERROR    |  5317 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f5808736a90>>: cannot schedule new futures after shutdown
2021-10-15 06:51:12.423 | INFO     |  6976 | __main__:main:46 | Starting Audio Service
2021-10-15 06:51:12.424 | INFO     |  6976 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-15 06:51:12.429 | INFO     |  6976 | mycroft_bus_client.client.client | Connected
2021-10-15 06:51:12.431 | INFO     |  6976 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-15 06:51:12.434 | WARNING  |  6976 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
2021-10-15 06:51:12.778 | ERROR    |  6976 | mycroft.tts.mimic_tts:validate_connection:226 | Mimic executable not found
2021-10-15 06:51:12.779 | ERROR    |  6976 | mycroft.tts.tts:create:625 | The TTS could not be loaded.
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 221, in validate_connection
    subprocess.call([mimic_bin, '--version'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 614, in create
    tts.validator.validate()
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 500, in validate
    self.validate_connection()
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 229, in validate_connection
    from err
Exception: Mimic was not found. Run install-mimic.sh to install it.
2021-10-15 06:51:12.781 | ERROR    |  6976 | __main__:on_error:37 | Audio service failed to launch (Exception('Mimic was not found. Run install-mimic.sh to install it.')).
2021-10-15 06:51:12.800 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:12.801 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:12.801 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:12.801 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:12.802 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:12.802 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:12.802 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:14.009 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:14.398 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:14.784 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:15.417 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:16.441 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:24.036 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:24.447 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:24.830 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:25.197 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:25.749 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:26.230 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:27.247 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:32.868 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-15 06:51:34.371 | ERROR    |  6976 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
Exception ignored in: <module 'threading' from '/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
