2021-10-26 10:26:17.595 | INFO     |  5721 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-26 10:26:17.598 | INFO     |  5721 | mycroft_bus_client.client.client | Connected
2021-10-26 10:26:17.613 | INFO     |  5721 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-26 10:26:17.623 | INFO     |  5721 | mycroft.skills.msm_wrapper:create_msm:96 | Acquiring lock to instantiate MSM
2021-10-26 10:26:20.784 | INFO     |  5721 | msm.mycroft_skills_manager | building SkillEntry objects for all skills
2021-10-26 10:26:21.023 | INFO     |  5721 | mycroft.skills.msm_wrapper:create_msm:112 | Releasing MSM instantiation lock.
2021-10-26 10:26:21.024 | INFO     |  5721 | mycroft.skills.skill_updater:_log_next_download_time:267 | Next scheduled skill update: 2021-10-26 10:26:20.023960
2021-10-26 10:26:21.024 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-pairing
2021-10-26 10:26:21.296 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:21.306 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-pairing
2021-10-26 10:26:21.306 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:21.308 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-pairing.mycroftai
2021-10-26 10:26:21.316 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-pairing.mycroftai/settings.json
2021-10-26 10:26:21.324 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-pairing.mycroftai
2021-10-26 10:26:21.325 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-pairing.mycroftai/settings.json
2021-10-26 10:26:21.328 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-pairing.mycroftai loaded successfully
2021-10-26 10:26:21.328 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-volume
2021-10-26 10:26:22.984 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:22.994 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for mycroft-volume
2021-10-26 10:26:23.762 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-volume
2021-10-26 10:26:23.762 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:23.763 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-volume.mycroftai
2021-10-26 10:26:23.772 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-volume.mycroftai/settings.json
2021-10-26 10:26:23.877 | ERROR    |  5721 | VolumeSkill | Couldn't allocate mixer, ALSAAudioError('No such file or directory [default]')
2021-10-26 10:26:26.882 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-volume.mycroftai
2021-10-26 10:26:26.882 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-volume.mycroftai/settings.json
2021-10-26 10:26:26.916 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-volume.mycroftai loaded successfully
2021-10-26 10:26:26.917 | INFO     |  5721 | __main__:on_started:177 | Skills service is starting up.
2021-10-26 10:26:26.966 | INFO     |  5721 | __main__:_update_system:154 | Attempting system update...
2021-10-26 10:26:29.968 | INFO     |  5721 | mycroft.enclosure.display_manager:_write_data:70 | Display Manager is creating /tmp/mycroft/ipc/managers/disp_info
2021-10-26 10:26:29.968 | INFO     |  5721 | __main__:_ensure_device_is_paired:133 | Device not paired, invoking the pairing skill
2021-10-26 10:26:29.969 | INFO     |  5721 | __main__:on_alive:181 | Skills service is alive.
2021-10-26 10:26:29.978 | INFO     |  5721 | msm.mycroft_skills_manager | building SkillEntry objects for all skills
2021-10-26 10:26:30.160 | INFO     |  5721 | PairingSkill | Communicating account URL to user
2021-10-26 10:26:30.549 | WARNING  |  5721 | msm.mycroft_skills_manager | No such default skill: mycroft-pandora
2021-10-26 10:26:30.550 | INFO     |  5721 | mycroft.skills.skill_manager:run:234 | Not all default skills are installed, performing skill update...
2021-10-26 10:26:30.550 | INFO     |  5721 | mycroft.skills.skill_updater:update_skills:149 | Beginning skill update...
2021-10-26 10:26:30.599 | INFO     |  5721 | msm.mycroft_skills_manager | building SkillEntry objects for all skills
2021-10-26 10:26:30.922 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:30.951 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/fallback-unknown
2021-10-26 10:26:30.956 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/fallback-wolfram-alpha
2021-10-26 10:26:30.962 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-alarm
2021-10-26 10:26:30.970 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-audio-record
2021-10-26 10:26:30.975 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-configuration
2021-10-26 10:26:30.976 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-date-time
2021-10-26 10:26:30.986 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-hello-world
2021-10-26 10:26:30.986 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-installer
2021-10-26 10:26:30.994 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-naptime
2021-10-26 10:26:30.995 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-npr-news
2021-10-26 10:26:30.999 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-personal
2021-10-26 10:26:30.999 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-ip
2021-10-26 10:26:31.000 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/fallback-duckduckgo
2021-10-26 10:26:31.007 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-playback-control
2021-10-26 10:26:31.008 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-reminder
2021-10-26 10:26:31.028 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-joke
2021-10-26 10:26:31.088 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-singing
2021-10-26 10:26:32.077 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:32.149 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:32.263 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:32.273 | INFO     |  5721 | msm.skill_entry | Successfully installed fallback-unknown
2021-10-26 10:26:32.276 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:32.280 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-speak
2021-10-26 10:26:32.343 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:32.350 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for mycroft-audio-record
2021-10-26 10:26:32.419 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for mycroft-ip
2021-10-26 10:26:32.495 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:32.504 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-naptime
2021-10-26 10:26:32.505 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:32.507 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-spelling
2021-10-26 10:26:32.551 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:32.552 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:32.556 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:32.566 | ERROR    |  5721 | msm.mycroft_skills_manager | Error running install_or_update on homeassistant.mycroftai: MergeConflict
2021-10-26 10:26:32.594 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-stop
2021-10-26 10:26:32.617 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:32.629 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for mycroft-joke
2021-10-26 10:26:32.633 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-hello-world
2021-10-26 10:26:32.633 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:32.634 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-support
2021-10-26 10:26:32.679 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:32.712 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for mycroft-date-time
2021-10-26 10:26:32.739 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-playback-control
2021-10-26 10:26:32.739 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:32.740 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/mycroft-timer
2021-10-26 10:26:32.746 | INFO     |  5721 | msm.skill_entry | Nothing new for mycroft-volume
2021-10-26 10:26:32.777 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-reminder
2021-10-26 10:26:32.777 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:32.781 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-weather
2021-10-26 10:26:32.792 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for mycroft-npr-news
2021-10-26 10:26:32.820 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:32.906 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for mycroft-volume
2021-10-26 10:26:33.058 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:33.059 | INFO     |  5721 | msm.skill_entry | Nothing new for mycroft-pairing
2021-10-26 10:26:33.104 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:33.127 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for mycroft-fallback-duck-duck-go
2021-10-26 10:26:33.129 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:33.163 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for fallback-wolfram-alpha
2021-10-26 10:26:33.234 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-version-checker
2021-10-26 10:26:33.251 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:33.308 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for mycroft-alarm
2021-10-26 10:26:33.315 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:33.362 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-personal
2021-10-26 10:26:33.362 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:33.363 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-wiki
2021-10-26 10:26:33.374 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:33.403 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-spelling
2021-10-26 10:26:33.404 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:33.405 | INFO     |  5721 | msm.skill_entry | Downloading skill: https://github.com/MycroftAI/skill-query
2021-10-26 10:26:33.437 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:33.455 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for mycroft-configuration
2021-10-26 10:26:33.812 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:33.831 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for mycroft-support-helper
2021-10-26 10:26:34.135 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:34.233 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-stop
2021-10-26 10:26:34.233 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:34.310 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:34.322 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:34.345 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:34.370 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:34.382 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-version-checker
2021-10-26 10:26:34.383 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:34.439 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for mycroft-installer
2021-10-26 10:26:34.440 | INFO     |  5721 | msm.skill_entry | Successfully installed fallback-query
2021-10-26 10:26:34.440 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:34.447 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for mycroft-wiki
2021-10-26 10:26:34.448 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:34.462 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:34.501 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-speak
2021-10-26 10:26:34.502 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:34.523 | INFO     |  5721 | msm.skill_entry | Installing requirements.txt for mycroft-weather
2021-10-26 10:26:34.690 | ERROR    |  5721 | msm.mycroft_skills_manager | Error running install_or_update on homeassistant: MergeConflict
2021-10-26 10:26:34.780 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-audio-record
2021-10-26 10:26:34.780 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:35.234 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:35.266 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-timer
2021-10-26 10:26:35.267 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:35.458 | INFO     |  5721 | msm.skill_entry | Installing system requirements...
2021-10-26 10:26:35.486 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-singing
2021-10-26 10:26:35.487 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:35.891 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-ip
2021-10-26 10:26:35.892 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:36.869 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-joke
2021-10-26 10:26:36.870 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:51.966 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-date-time
2021-10-26 10:26:51.966 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:54.852 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-npr-news
2021-10-26 10:26:54.852 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:26:56.733 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-fallback-duck-duck-go
2021-10-26 10:26:56.733 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:27:00.497 | INFO     |  5721 | PairingSkill | Initiating device pairing sequence...
2021-10-26 10:27:00.498 | INFO     |  5721 | PairingSkill | Retrieving pairing code from device API...
2021-10-26 10:27:00.571 | INFO     |  5721 | PairingSkill | Pairing code obtained: HJCMW7
2021-10-26 10:27:00.572 | INFO     |  5721 | PairingSkill | Communicating pairing URL to user
2021-10-26 10:27:00.584 | INFO     |  5721 | msm.skill_entry | Successfully installed fallback-wolfram-alpha
2021-10-26 10:27:00.584 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:27:01.447 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-alarm
2021-10-26 10:27:01.447 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:27:03.997 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-configuration
2021-10-26 10:27:03.998 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:27:05.912 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-support-helper
2021-10-26 10:27:05.912 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:27:06.862 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-installer
2021-10-26 10:27:06.862 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:27:08.656 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-wiki
2021-10-26 10:27:08.657 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:27:09.600 | INFO     |  5721 | msm.skill_entry | Successfully installed mycroft-weather
2021-10-26 10:27:09.601 | INFO     |  5721 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-26 10:27:09.646 | INFO     |  5721 | mycroft.skills.skill_updater:_log_next_download_time:267 | Next scheduled skill update: 2021-10-26 11:27:09.645964
2021-10-26 10:27:09.646 | INFO     |  5721 | mycroft.skills.skill_updater:update_skills:170 | Skill update complete
2021-10-26 10:27:09.647 | INFO     |  5721 | mycroft.skills.skill_manager:_load_on_startup:273 | Loading installed skills...
2021-10-26 10:27:09.648 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-ip.mycroftai
2021-10-26 10:27:09.684 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-ip.mycroftai/settings.json
2021-10-26 10:27:09.699 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-ip.mycroftai
2021-10-26 10:27:09.700 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-ip.mycroftai/settings.json
2021-10-26 10:27:09.700 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-ip.mycroftai loaded successfully
2021-10-26 10:27:09.702 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-reminder.mycroftai
2021-10-26 10:27:09.737 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-reminder.mycroftai/settings.json
2021-10-26 10:27:09.774 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-reminder.mycroftai
2021-10-26 10:27:09.777 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-reminder.mycroftai/settings.json
2021-10-26 10:27:09.782 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-reminder.mycroftai loaded successfully
2021-10-26 10:27:09.786 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-installer.mycroftai
2021-10-26 10:27:09.792 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-installer.mycroftai/settings.json
2021-10-26 10:27:09.825 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-installer.mycroftai
2021-10-26 10:27:09.825 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-installer.mycroftai/settings.json
2021-10-26 10:27:09.827 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-installer.mycroftai loaded successfully
2021-10-26 10:27:09.828 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-version-checker.mycroftai
2021-10-26 10:27:09.834 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-version-checker.mycroftai/settings.json
2021-10-26 10:27:09.865 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-version-checker.mycroftai
2021-10-26 10:27:09.866 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-version-checker.mycroftai/settings.json
2021-10-26 10:27:09.870 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-version-checker.mycroftai loaded successfully
2021-10-26 10:27:09.870 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-singing.mycroftai
2021-10-26 10:27:09.875 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-singing.mycroftai/settings.json
2021-10-26 10:27:09.891 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-singing.mycroftai
2021-10-26 10:27:09.892 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-singing.mycroftai/settings.json
2021-10-26 10:27:09.899 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-singing.mycroftai loaded successfully
2021-10-26 10:27:09.899 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-joke.mycroftai
2021-10-26 10:27:09.904 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-joke.mycroftai/settings.json
2021-10-26 10:27:09.926 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-joke.mycroftai
2021-10-26 10:27:09.929 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-joke.mycroftai/settings.json
2021-10-26 10:27:09.929 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-joke.mycroftai loaded successfully
2021-10-26 10:27:09.930 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-timer.mycroftai
2021-10-26 10:27:09.969 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-timer.mycroftai/settings.json
2021-10-26 10:27:10.031 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-timer.mycroftai
2021-10-26 10:27:10.037 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-timer.mycroftai/settings.json
2021-10-26 10:27:10.038 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-timer.mycroftai loaded successfully
2021-10-26 10:27:10.039 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: homeassistant.mycroftai
2021-10-26 10:27:10.368 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/homeassistant.mycroftai/settings.json
2021-10-26 10:27:10.369 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/homeassistant.mycroftai/settings.json
2021-10-26 10:27:10.389 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill homeassistant.mycroftai loaded successfully
2021-10-26 10:27:10.390 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-alarm.mycroftai
2021-10-26 10:27:10.403 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-alarm.mycroftai/settings.json
2021-10-26 10:27:10.404 | ERROR    |  5721 | AlarmSkill | Couldn't allocate mixer, ALSAAudioError('No such file or directory [default]')
2021-10-26 10:27:10.434 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-alarm.mycroftai
2021-10-26 10:27:10.434 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-alarm.mycroftai/settings.json
2021-10-26 10:27:10.435 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-alarm.mycroftai loaded successfully
2021-10-26 10:27:10.435 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-naptime.mycroftai
2021-10-26 10:27:10.439 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-naptime.mycroftai/settings.json
2021-10-26 10:27:10.445 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-naptime.mycroftai
2021-10-26 10:27:10.445 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-naptime.mycroftai/settings.json
2021-10-26 10:27:10.446 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-naptime.mycroftai loaded successfully
2021-10-26 10:27:10.447 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-spelling.mycroftai
2021-10-26 10:27:10.449 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-spelling.mycroftai/settings.json
2021-10-26 10:27:10.459 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-spelling.mycroftai
2021-10-26 10:27:10.460 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-spelling.mycroftai/settings.json
2021-10-26 10:27:10.461 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-spelling.mycroftai loaded successfully
2021-10-26 10:27:10.461 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-fallback-duck-duck-go.mycroftai
2021-10-26 10:27:10.477 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai/settings.json
2021-10-26 10:27:10.501 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-fallback-duck-duck-go.mycroftai
2021-10-26 10:27:10.502 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai/settings.json
2021-10-26 10:27:10.502 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-fallback-duck-duck-go.mycroftai loaded successfully
2021-10-26 10:27:10.503 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-npr-news.mycroftai
2021-10-26 10:27:10.570 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-npr-news.mycroftai/settings.json
2021-10-26 10:27:11.586 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-npr-news.mycroftai
2021-10-26 10:27:11.587 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-npr-news.mycroftai/settings.json
2021-10-26 10:27:11.588 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-npr-news.mycroftai loaded successfully
2021-10-26 10:27:11.588 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-support-helper.mycroftai
2021-10-26 10:27:11.603 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-support-helper.mycroftai/settings.json
2021-10-26 10:27:11.614 | INFO     |  5721 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-support-helper.mycroftai
2021-10-26 10:27:11.615 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-support-helper.mycroftai/settings.json
2021-10-26 10:27:11.626 | INFO     |  5721 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-support-helper.mycroftai loaded successfully
2021-10-26 10:27:11.627 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-weather.mycroftai
2021-10-26 10:27:11.643 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-weather.mycroftai/settings.json
2021-10-26 10:27:11.779 | ERROR    |  5721 | mycroft_bus_client.client.client | === ConnectionResetError(104, 'Connection reset by peer') ===
Traceback (most recent call last):
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 305, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 53, in read
    if not read_callback():
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 271, in read
    op_code, frame = self.sock.recv_data_frame(True)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 340, in recv_data_frame
    frame = self.recv_frame()
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 374, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 449, in _recv
    return recv(self.sock, bufsize)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 81, in recv
    bytes_ = sock.recv(bufsize)
ConnectionResetError: [Errno 104] Connection reset by peer
2021-10-26 10:27:11.781 | ERROR    |  5721 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-weather.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 305, in _create_skill_instance
    self.instance._register_decorated()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 749, in _register_decorated
    self.register_intent(intent, method)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 989, in register_intent
    return self._register_adapt_intent(intent_parser, handler)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 968, in _register_adapt_intent
    self.intent_service.register_adapt_intent(name, intent_parser)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 84, in register_adapt_intent
    self.bus.emit(Message("register_intent", intent_parser.__dict__))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-26 10:27:11.782 | ERROR    |  5721 | mycroft_bus_client.client.client | Exception closing websocket: ConnectionResetError(104, 'Connection reset by peer')
2021-10-26 10:27:11.783 | WARNING  |  5721 | mycroft_bus_client.client.client | Message Bus Client will reconnect in 5 seconds.
2021-10-26 10:27:11.783 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-speak.mycroftai
2021-10-26 10:27:11.786 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-speak.mycroftai/settings.json
2021-10-26 10:27:11.791 | ERROR    |  5721 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-speak.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-26 10:27:11.791 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-audio-record.mycroftai
2021-10-26 10:27:11.795 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-audio-record.mycroftai/settings.json
2021-10-26 10:27:11.800 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-audio-record.mycroftai/settings.json
2021-10-26 10:27:11.822 | ERROR    |  5721 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-audio-record.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-26 10:27:11.823 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-stop.mycroftai
2021-10-26 10:27:11.827 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-stop.mycroftai/settings.json
2021-10-26 10:27:11.831 | ERROR    |  5721 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-stop.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-26 10:27:11.832 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-hello-world.mycroftai
2021-10-26 10:27:11.835 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-hello-world.mycroftai/settings.json
2021-10-26 10:27:11.839 | ERROR    |  5721 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-hello-world.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-26 10:27:11.840 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-date-time.mycroftai
2021-10-26 10:27:12.341 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-date-time.mycroftai/settings.json
2021-10-26 10:27:12.346 | ERROR    |  5721 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-date-time.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-26 10:27:12.347 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-configuration.mycroftai
2021-10-26 10:27:12.352 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-configuration.mycroftai/settings.json
2021-10-26 10:27:12.358 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-configuration.mycroftai/settings.json
2021-10-26 10:27:12.368 | ERROR    |  5721 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-configuration.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-26 10:27:12.369 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: fallback-query.mycroftai
2021-10-26 10:27:12.373 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/fallback-query.mycroftai/settings.json
2021-10-26 10:27:12.377 | INFO     |  5721 | QuestionsAnswersSkill | Removing all handlers...
2021-10-26 10:27:12.377 | ERROR    |  5721 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/fallback-query.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/fallback_skill.py", line 199, in default_shutdown
    super(FallbackSkill, self).default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-26 10:27:12.378 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-personal.mycroftai
2021-10-26 10:27:12.381 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-personal.mycroftai/settings.json
2021-10-26 10:27:12.385 | ERROR    |  5721 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-personal.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 305, in _create_skill_instance
    self.instance._register_decorated()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 749, in _register_decorated
    self.register_intent(intent, method)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 985, in register_intent
    return self.register_intent_file(intent_parser, handler)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1022, in register_intent_file
    self.intent_service.register_padatious_intent(name, filename)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 129, in register_padatious_intent
    self.bus.emit(Message("padatious:register_intent", data))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-26 10:27:12.385 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: fallback-wolfram-alpha.mycroftai
2021-10-26 10:27:12.408 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/fallback-wolfram-alpha.mycroftai/settings.json
2021-10-26 10:27:12.414 | ERROR    |  5721 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/fallback-wolfram-alpha.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-26 10:27:12.415 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-wiki.mycroftai
2021-10-26 10:27:12.419 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-wiki.mycroftai/settings.json
2021-10-26 10:27:12.423 | ERROR    |  5721 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-wiki.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-26 10:27:12.424 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: fallback-unknown.mycroftai
2021-10-26 10:27:12.427 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/fallback-unknown.mycroftai/settings.json
2021-10-26 10:27:12.431 | INFO     |  5721 | UnknownSkill | Removing all handlers...
2021-10-26 10:27:12.431 | ERROR    |  5721 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/fallback-unknown.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/fallback_skill.py", line 199, in default_shutdown
    super(FallbackSkill, self).default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-26 10:27:12.432 | INFO     |  5721 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-playback-control.mycroftai
2021-10-26 10:27:12.436 | INFO     |  5721 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-playback-control.mycroftai/settings.json
2021-10-26 10:27:12.441 | ERROR    |  5721 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-playback-control.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-26 10:27:12.441 | INFO     |  5721 | mycroft.skills.skill_manager:_load_on_startup:275 | Skills all loaded!
2021-10-26 10:27:16.787 | INFO     |  5721 | mycroft_bus_client.client.client | Connected
2021-10-26 10:27:30.948 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-pairing.mycroftai/settings.json
2021-10-26 10:27:31.251 | INFO     |  5721 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-timer.mycroftai/settings.json
